variable "region" {}
variable "ami" {}
variable "int_type" {}
variable "subnet" {}
variable "sec_grp" {}
variable "instance_count" {}
variable "key_pair" {}
variable "profile" {}
variable "instance_name" {}